// <auto-generated/>
#nullable enable
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Cabazure.Client.Authentication
{
    internal class AzureAuthenticationHandler
        : DelegatingHandler
    {
        private readonly IBearerTokenProvider tokenProvider;

        public AzureAuthenticationHandler(
            IBearerTokenProvider tokenProvider)
        {
            this.tokenProvider = tokenProvider;     
        }

        protected async override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            request.Headers.Authorization = await tokenProvider.GetTokenAsync(cancellationToken);

            return await base.SendAsync(request, cancellationToken);
        }
    }
}
#nullable disable