// <auto-generated/>
#nullable enable
using System;

namespace Cabazure.Client.Authentication
{
    internal class DateTimeProvider
        : IDateTimeProvider
    {
        public DateTimeOffset GetDateTime()
            => DateTimeOffset.UtcNow;
    }
}
#nullable disable