// <auto-generated/>
#nullable enable
using System.Net.Http.Headers;

namespace Cabazure.Client.Authentication;

internal interface IBearerTokenProvider
{
    Task<AuthenticationHeaderValue> GetTokenAsync(
        CancellationToken cancellationToken);
}
#nullable disable