using System.Text;
using Microsoft.CodeAnalysis;

namespace Cabazure.Client.SourceGenerator;

[Generator]
public class ClientInitializationGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ClientInitializationSyntaxReceiver());

        context.RegisterForPostInitialization(c =>
            c.AddSource(
            "ClientInitialization.g.cs",
            """
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Text.Json;
            using Cabazure.Client;
            using Microsoft.Extensions.Options;

            namespace Microsoft.Extensions.DependencyInjection
            {
                internal static partial class ClientInitialization
                {
                    internal static partial IServiceCollection AddCabazureClient<TOptions>(
                        this IServiceCollection services,
                        string clientName,
                        Action<JsonSerializerOptions>? jsonOptions,
                        Action<TOptions>? clientOptions,
                        Action<IHttpClientBuilder>? builder = default)
                        where TOptions : class, ICabazureClientOptions;

                    internal static partial IServiceCollection AddCabazureClient(
                        this IServiceCollection services,
                        string clientName,
                        Action<JsonSerializerOptions>? jsonOptions,
                        Action<IHttpClientBuilder> builder);
                }
            }
            #nullable disable
            """));
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not ClientInitializationSyntaxReceiver receiver)
        {
            return;
        }

        foreach (var diagnostic in receiver.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");

        var usingStatements = receiver.Endpoints
            .Select(e => e.Namespace)
            .OfType<string>()
            .Append("System")
            .Append("System.Net.Http")
            .Append("System.Text.Json")
            .Append("System.Collections.Generic")
            .Append("Azure.Core")
            .Append("Cabazure.Client")
            .Append("Cabazure.Client.Authentication")
            .Append("Cabazure.Client.Builder")
            .Append("Microsoft.Extensions.DependencyInjection.Extensions")
            .Append("Microsoft.Extensions.Options")
            .Distinct()
            .OrderByDescending(us => us.StartsWith("System"))
            .ThenBy(us => us)
            .ToArray();
        if (usingStatements.Length > 0)
        {
            foreach (var us in usingStatements)
            {
                source.AppendLine($"using {us};");
            }
            source.AppendLine();
        }

        source.AppendLine($$"""
            namespace Microsoft.Extensions.DependencyInjection
            {
                internal static partial class ClientInitialization
                {
                    internal static partial IServiceCollection AddCabazureClient<TOptions>(
                        this IServiceCollection services,
                        string clientName,
                        Action<JsonSerializerOptions>? jsonOptions,
                        Action<TOptions>? clientOptions,
                        Action<IHttpClientBuilder>? builder)
                        where TOptions : class, ICabazureClientOptions
                    {
                        if (clientOptions != null)
                        {
                            services
                                .AddOptions<TOptions>()
                                .Configure(clientOptions);
                        }
            
                        void ConfigureHttpClient(IServiceProvider services, HttpClient client)
                            => client.BaseAddress = services
                                .GetRequiredService<IOptions<TOptions>>()
                                .Value
                                .GetBaseAddress();
            
                        void ConfigureAuthHandler(IList<DelegatingHandler> handlers, IServiceProvider services)
                        {
                            var options = services
                                .GetRequiredService<IOptions<TOptions>>()
                                .Value;
            
                            if (options is ICabazureAuthClientOptions authOptions)
                            {
                                var scope = authOptions.GetScope();
                                var credential = authOptions.GetCredential();
            
                                var tokenProvider = new BearerTokenProvider(
                                    new TokenRequestContext(new [] { scope }),
                                    credential,
                                    new DateTimeProvider());
            
                                handlers.Add(new AzureAuthenticationHandler(tokenProvider));
                            }
                        }
            
                        void BuildHttpClient(IHttpClientBuilder b)
                        {
                            b.ConfigureHttpClient(ConfigureHttpClient);
                            b.ConfigureAdditionalHttpMessageHandlers(ConfigureAuthHandler);
                            builder?.Invoke(b);
                        }
            
                        return services.AddCabazureClient(
                            clientName,
                            jsonOptions,
                            BuildHttpClient);
                    }

                    internal static partial IServiceCollection AddCabazureClient(
                        this IServiceCollection services,
                        string clientName,
                        Action<JsonSerializerOptions>? jsonOptions,
                        Action<IHttpClientBuilder> builder)
                    {
                        if (jsonOptions != null)
                        {
                            services
                                .AddOptions<JsonSerializerOptions>(clientName)
                                .Configure(jsonOptions);
                        }

                        var clientBuilder = services.AddHttpClient(clientName);
                        builder.Invoke(clientBuilder);
            
                        services.TryAddSingleton<IClientSerializer, ClientSerializer>();
                        services.TryAddSingleton<IMessageRequestFactory, MessageRequestFactory>();
            """);

        foreach (var endpoint in receiver.Endpoints)
        {
            source.AppendLine($$"""
                            services.TryAddSingleton<{{endpoint.InterfaceName}}, {{endpoint.ClassName}}>();
                """);
        }

        source.AppendLine("""
                        return services;
                    }
            """);

        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine("#nullable disable");

        context.AddSource(
            $"ClientInitialization.Implementation.g.cs",
            source.ToString());
    }
}