//HintName: ClientInitialization.Implementation.g.cs
// <auto-generated/>
using System.Text.Json;
using Cabazure.Client.Builder;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Microsoft.Extensions.DependencyInjection;

internal static partial class ClientInitialization
{
    internal static partial IServiceCollection AddCabazureClient(
        this IServiceCollection services,
        string clientName,
        Action<IHttpClientBuilder> builder,
        Action<JsonSerializerOptions> jsonOptions)
    {
        var clientBuilder = services.AddHttpClient(clientName);
        builder.Invoke(clientBuilder);

        services
            .AddOptions<JsonSerializerOptions>(clientName)
            .Configure(jsonOptions);

        services.TryAddSingleton<IClientSerializer, ClientSerializer>();
        services.TryAddSingleton<IMessageRequestFactory, MessageRequestFactory>();
        services.TryAddSingleton<ITestEndpoint, TestEndpoint>();
        return services;
    }
}
