//HintName: ClientInitialization.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using Cabazure.Client;
using Microsoft.Extensions.Options;

namespace Microsoft.Extensions.DependencyInjection
{
    internal static partial class ClientInitialization
    {
        internal static partial IServiceCollection AddCabazureClient<TOptions>(
            this IServiceCollection services,
            string clientName,
            Action<JsonSerializerOptions>? jsonOptions,
            Action<TOptions>? clientOptions,
            Action<IHttpClientBuilder>? builder = default)
            where TOptions : class, ICabazureClientOptions;

        internal static partial IServiceCollection AddCabazureClient(
            this IServiceCollection services,
            string clientName,
            Action<JsonSerializerOptions>? jsonOptions,
            Action<IHttpClientBuilder> builder);
    }
}
#nullable disable