//HintName: TestEndpoint.g.cs
// <auto-generated/>
#nullable enable
using System.Net;
using System.Net.Http;
using System.Runtime.CompilerServices;
using Cabazure.Client;
using Cabazure.Client.Builder;

namespace Test
{
    [CompilerGenerated]
    internal partial class TestEndpoint : ITestEndpoint
    {
        private readonly IHttpClientFactory factory;
        private readonly IMessageRequestFactory requestFactory;
    
        public TestEndpoint(
            IHttpClientFactory factory,
            IMessageRequestFactory requestFactory)
        {
            this.factory = factory;
            this.requestFactory = requestFactory;
        }

        public async Task<StreamResponse> ExecuteAsync(
            string result,
            CancellationToken cancellationToken)
        {
            var client = factory.CreateClient("ClientName");
    
            using var requestMessage = requestFactory
                .FromTemplate("ClientName", "/items/{result}")
                .WithPathParameter("result", result)
                .Build(HttpMethod.Get);
    
            var streamSendResult = await client
                .SendStreamAsync(requestMessage, null, cancellationToken);
    
            return await requestFactory
                .FromResponse("ClientName", streamSendResult.Response)
                .AddSuccessResponse(HttpStatusCode.OK)
                .WithStreamTimeout(streamSendResult.TimeoutCts, streamSendResult.Timeout)
                .GetStreamAsync(cancellationToken);
        }
    }
}
#nullable disable
