//HintName: Builder.IMessageRequestFactory.g.cs
// <auto-generated/>
#nullable enable
using System.Net.Http;

namespace Cabazure.Client.Builder
{
    internal interface IMessageRequestFactory
    {
        IMessageRequestBuilder FromTemplate(string clientName, string template);

        IMessageResponseBuilder FromResponse(string clientName, HttpResponseMessage? response);
    }
}
#nullable disable