//HintName: Authentication.AzureAuthenticationHandler.g.cs
// <auto-generated/>
#nullable enable
namespace Cabazure.Client.Authentication;

internal class AzureAuthenticationHandler
    : DelegatingHandler
{
    private readonly IBearerTokenProvider tokenProvider;

    public AzureAuthenticationHandler(
        IBearerTokenProvider tokenProvider)
    {
        this.tokenProvider = tokenProvider;     
    }

    protected async override Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
        request.Headers.Authorization = await tokenProvider.GetTokenAsync(cancellationToken);

        return await base.SendAsync(request, cancellationToken);
    }
}
#nullable disable