//HintName: HeaderAttribute.g.cs
// <auto-generated/>
#nullable enable
using System.Diagnostics.CodeAnalysis;

namespace Cabazure.Client;

/// <summary>
/// Specifies that a parameter should be bound to a request header.
/// </summary>
/// <param name="name">The name of the request header.</param>
[ExcludeFromCodeCoverage]
[AttributeUsage(
    AttributeTargets.Parameter | AttributeTargets.Property,
    Inherited = false,
    AllowMultiple = false)]
internal sealed class HeaderAttribute(
    string name,
    string? formatString = null)
    : Attribute
{
    public string Name { get; } = name;

    public string? FormatString { get; } = formatString;
}
#nullable disable