//HintName: Authentication.DateTimeProvider.g.cs
// <auto-generated/>
#nullable enable
namespace Cabazure.Client.Authentication;

internal class DateTimeProvider
    : IDateTimeProvider
{
    public DateTimeOffset GetDateTime()
        => DateTimeOffset.UtcNow;
}
#nullable disable