//HintName: Builder.HttpClientExtensions.g.cs
// <auto-generated/>
#nullable enable
using System.Net.Http;

namespace Cabazure.Client.Builder
{
    internal static class HttpClientExtensions
    {
        public static HttpClient WithRequestOptions(
            this HttpClient httpClient,
            IRequestOptions? requestOptions)
        {
            if (requestOptions is { Timeout: { Ticks: > 0 } timeout })
            {
                httpClient.Timeout = timeout;
            }

            return httpClient;
        }
    }
}
#nullable disable