//HintName: Authentication.IDateTimeProvider.g.cs
// <auto-generated/>
#nullable enable
using System;

namespace Cabazure.Client.Authentication
{
    internal interface IDateTimeProvider
    {
        DateTimeOffset GetDateTime();
    }
}
#nullable disable