using System.Text;
using Cabazure.Client.SourceGenerator.Descriptors;
using Cabazure.Client.SourceGenerator.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cabazure.Client.SourceGenerator;

[Generator]
public class ClientInitializationGenerator : ISourceGenerator, ISyntaxContextReceiver
{
    private readonly List<EndpointDescriptor> endpoints = [];
    private readonly List<InitializationDescriptor> initializations = [];

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => this);
    }

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        if (context.Node is not AttributeSyntax attribute)
        {
            return;
        }

        var attributeType = context.SemanticModel
            .GetSymbolInfo(attribute).Symbol?
            .ContainingType
            .ToString();

        if (attributeType == TypeConstants.ClientEndpointAttribute)
        {
            endpoints.Add(
                EndpointDescriptor.FromAttribute(
                    context.SemanticModel,
                    attribute));
        }
        else if (attributeType == TypeConstants.ClientInitializationAttribute)
        {
            initializations.Add(
                InitializationDescriptor.FromAttribute(
                    context.SemanticModel,
                    attribute));
        }
    }

    public void Execute(GeneratorExecutionContext context)
    {
        foreach (var methods in initializations.GroupBy(i => i.DeclaringType))
        {
            var type = methods.Key;
            if (!type.IsPartialClass)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        DiagnosticDescriptors.InitializationNotInPartialClass,
                        null, //initMethods.Key.GetLocation(),
                        type.Name));

                continue;
            }


            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");

            var ns = type.Namespace;
            var usingStatements = endpoints
                .Select(e => e.Namespace)
                .OfType<string>()
                .Append("System.Text.Json")
                .Append("Cabazure.Client.Builder")
                .Append("Microsoft.Extensions.DependencyInjection")
                .Append("Microsoft.Extensions.DependencyInjection.Extensions")
                .Distinct()
                .Where(us => us != ns)
                .OrderByDescending(us => us.StartsWith("System"))
                .ThenBy(us => us)
                .ToArray();
            if (usingStatements.Length > 0)
            {
                foreach (var us in usingStatements)
                {
                    source.AppendLine($"using {us};");
                }
                source.AppendLine();
            }

            if (ns != null)
            {
                source.AppendLine($"namespace {ns};\n");
            }

            source.AppendLine($$"""
                {{type.Signature}}
                {
                """);

            foreach (var method in methods)
            {
                source.AppendLine($$"""
                        {{method.Signature}}
                        {
                            var clientBuilder = services.AddHttpClient("{{method.ClientName}}");
                            {{method.BuilderName}}?.Invoke(clientBuilder);

                            {{method.ServicesName}}
                                .AddOptions<JsonSerializerOptions>("{{method.ClientName}}")
                                .Configure({{method.JsonOptionsName}});

                            {{method.ServicesName}}.TryAddSingleton<IClientSerializer, ClientSerializer>();
                            {{method.ServicesName}}.TryAddSingleton<IMessageRequestFactory, MessageRequestFactory>();

                    """);

                var clientEndpoints = endpoints
                    .Where(e => e.ClientName == method.ClientName);

                foreach (var endpoint in clientEndpoints)
                {
                    source.AppendLine($$"""
                                {{method.ServicesName}}.AddSingleton<{{endpoint.InterfaceName}}, {{endpoint.ClassName}}>();
                        """);
                }

                source.AppendLine("""
                        }
                    """);
            }

            source.AppendLine("}");

            context.AddSource(
                $"{type.Name}.g.cs",
                source.ToString());
        }
    }
}
