// <auto-generated/>
#nullable enable
namespace Cabazure.Client.Builder
{
    internal interface IClientSerializer
    {
        T? Deserialize<T>(string clientName, string json);
        string Serialize(string clientName, object value);
    }
}
#nullable disable