// <auto-generated/>
#nullable enable
namespace Cabazure.Client.Builder;

internal interface IMessageRequestFactory
{
    IMessageRequestBuilder FromTemplate(string clientName, string template);

    IMessageResponseBuilder FromResponse(string clientName, HttpResponseMessage? response);
}
#nullable disable